version: '3'

services:

  api:
    container_name: challenge_marche_api
    image: node:10
    networks:
      - mongo_db
      - redis_db
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
      - redis
    working_dir: /app
    volumes:
      - ./API:/app
    environment:
      NODE_ENV: development
    env_file:
      - API/.env

  mongo:
    container_name: challenge_marche_mongo
    image: mongo
    networks:
      - mongo_db
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: root
      MONGODB_PASS: root
      MONGO_DATA_DIR: /data/db
    env_file:
      - API/.env

  redis:
    container_name: challenge_marche_redis
    image: redis
    networks:
      - redis_db
    command: redis-server
    ports:
      - "6379:6379"

networks:
  mongo_db:
  redis_db:
  webapp:

volumes:
  db_data:
